### ISSUE TITLE
The root logger has been used illegally.

### ISSUE THREAD

**Issue by oniatsu** [supabase-community/supabase-py#751]
# Bug report

## Describe the bug

The root logger has been used illegally.

The root logger is dirty just by importing the package.
The package should work without affecting the root logger.

## To Reproduce

1. `pip install supabase==2.4.1`
2. Run the code

code
```python
import logging

import supabase

logger = logging.getLogger(__name__)
print(logger.hasHandlers())
print(logger.handlers)

root_logger = logging.getLogger()
print(root_logger.handlers)
```

result
```
True
[]
[<StreamHandler <stderr> (NOTSET)>]
```

## Expected behavior

code
```python
import logging

# import supabase # comment out

logger = logging.getLogger(__name__)
print(logger.hasHandlers())
print(logger.handlers)

root_logger = logging.getLogger()
print(root_logger.handlers)
```

result
```
False
[]
[]
```

## System information

- OS: macOS
- Version of supabase-py: 2.4.1
- Version of Python: Python 3.11.5

**Comment by silentworks** [comment]
Closing this out as I believe it has been resolved.

**Comment by oniatsu** [comment]
@silentworks I checked with the latest version and it is not fixed.
```python
import logging

import supabase

logger = logging.getLogger(__name__)
print(logger.hasHandlers())
print(logger.handlers)

root_logger = logging.getLogger()
print(root_logger.handlers)
```

```shell
% pip list | grep supabase
supabase                  2.4.6

% python temp.py
True
[]
[<StreamHandler <stderr> (NOTSET)>]
```

**Comment by silentworks** [comment]
@oniatsu  I'm getting completely different results to you with the latest 2.4.6 release.

![image](https://github.com/supabase-community/supabase-py/assets/79497/5a8a331c-c4d9-43d3-ae6c-9363693fa8f6)

**Comment by oniatsu** [comment]
@silentworks I ran it again in a re-created venv environment and the results were the same as yours.
It may have been my environment. My apologies.
I will close it as it is probably not the problem.
